Repository AY2425S1-CS2103T-F14a-2/tp, pull requests merged in 2024-11, with the labels that each got.

#158 Make AddOrder command give warning only if there is duplicate pending order
  docs/UserGuide.md
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#133 Fix bug where EditPersonCommand unfilter displayed order list
  src/main/java/seedu/sellsavvy/model/person/Person.java
  src/main/java/seedu/sellsavvy/model/person/UniquePersonList.java
  src/test/java/seedu/sellsavvy/model/person/PersonTest.java
Labels: priority.Medium, severity.High, type.FeatureFlaw, alpha-bug

#162 Change GUI message displayed when there are no orders or customers
  src/main/java/seedu/sellsavvy/model/Model.java
  src/main/java/seedu/sellsavvy/model/person/Person.java
  src/main/java/seedu/sellsavvy/ui/OrderListPanel.java
  src/main/java/seedu/sellsavvy/ui/PersonListPanel.java
  src/main/resources/view/OrderListPanel.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/sellsavvy/model/person/PersonTest.java
Labels: type.Enhancement, priority.High, alpha-bug

#163 Move createCopy method from UniquePersonList to respective classes
  src/main/java/seedu/sellsavvy/model/order/Order.java
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/main/java/seedu/sellsavvy/model/person/Person.java
  src/main/java/seedu/sellsavvy/model/person/UniquePersonList.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderTest.java
  src/test/java/seedu/sellsavvy/model/person/PersonTest.java
  src/test/java/seedu/sellsavvy/model/person/UniquePersonListTest.java
Labels: type.Task, severity.Low

#166 Update test cases for EditOrderCommand
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/OrderCommandTestUtil.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#169 Fix visual bug where person's name too long is handled differently from item's name too long
  src/main/java/seedu/sellsavvy/ui/OrderCard.java
  src/main/java/seedu/sellsavvy/ui/OrderListPanel.java
  src/main/java/seedu/sellsavvy/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListPanel.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#178 Remove unused fields
  src/main/java/seedu/sellsavvy/ui/OrderCard.java
Labels: type.Bug, priority.Low, severity.VeryLow, alpha-bug

#176 Standardize usage of line breaks and periods in response messages
  src/main/java/seedu/sellsavvy/logic/Messages.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/ListOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/DeletePersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/FindPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/ListPersonCommand.java
  src/main/java/seedu/sellsavvy/model/order/Date.java
  src/main/java/seedu/sellsavvy/model/order/Quantity.java
  src/main/java/seedu/sellsavvy/model/order/Status.java
  src/main/java/seedu/sellsavvy/model/person/Address.java
  src/main/java/seedu/sellsavvy/model/person/Email.java
  src/main/java/seedu/sellsavvy/model/person/Name.java
  src/main/java/seedu/sellsavvy/model/person/Phone.java
  src/main/java/seedu/sellsavvy/model/tag/Tag.java
Labels: type.Bug, priority.Medium, severity.Low, alpha-bug

#182 Allow commands to be case-insensitive
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/ListOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddressBookParser.java
Labels: type.Enhancement, priority.High, severity.Medium, alpha-bug

#189 Update user guide wrt to warnings
  docs/UserGuide.md
Labels: priority.High, severity.High, type.DocumentationBug, alpha-bug

#186 Add aliases and short forms for commands
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/ListOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/DeletePersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/FindPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/ListPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddressBookParser.java
  src/test/java/seedu/sellsavvy/logic/LogicManagerTest.java
Labels: type.Enhancement, priority.High, severity.Medium, alpha-bug

#190 Add command aliases to user guide
  docs/UserGuide.md
Labels: priority.High, type.DocumentationBug, alpha-bug

#198 Update add command user guide
  docs/UserGuide.md
Labels: severity.Medium, type.DocumentationBug

#200 Update tips box
  docs/UserGuide.md
Labels: priority.Low, type.DocumentationBug, alpha-bug

#194 Update help command screenshot in user guide
  docs/images/helpMessage.png
Labels: priority.Medium, severity.Low, type.DocumentationBug, alpha-bug

#197 Add line breaks between command alias and format in user guide
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.DocumentationBug, alpha-bug

#202 Update user guide for duplicate handling
  docs/UserGuide.md
Labels: priority.High, severity.High, type.DocumentationBug, alpha-bug

#174 Updated filtered list test cases for unmark order and mark order
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/FindPersonCommand.java
  src/main/java/seedu/sellsavvy/model/ModelManager.java
  src/main/java/seedu/sellsavvy/model/order/Order.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/OrderCommandTestUtil.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommandTest.java
  src/test/java/seedu/sellsavvy/testutil/TypicalIndexes.java
Labels: priority.High, alpha-bug

#193 Add test cases for parsing command aliases
  src/test/java/seedu/sellsavvy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/sellsavvy/testutil/OrderUtil.java
  src/test/java/seedu/sellsavvy/testutil/PersonUtil.java
Labels: type.Task, priority.Medium, alpha-bug

#209 Enlarge screenshot for filterorder in user guide
  docs/images/filterCompletedOrders.png
Labels: priority.Low, severity.Low, type.DocumentationBug, alpha-bug

#212 Move hyperlink for addorder constraints up in user guide
  docs/UserGuide.md
Labels: priority.Low, severity.Medium, type.DocumentationBug, alpha-bug

#217 Standardise UML diagrams
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: priority.Low, severity.Low, type.DocumentationBug, alpha-bug

#210 Fix tag/customer/item duplicate handling
  src/main/java/seedu/sellsavvy/commons/util/StringUtil.java
  src/main/java/seedu/sellsavvy/logic/Messages.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/ListOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/DeletePersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java
  src/main/java/seedu/sellsavvy/model/AddressBook.java
  src/main/java/seedu/sellsavvy/model/Model.java
  src/main/java/seedu/sellsavvy/model/ModelManager.java
  src/main/java/seedu/sellsavvy/model/order/Date.java
  src/main/java/seedu/sellsavvy/model/order/Item.java
  src/main/java/seedu/sellsavvy/model/order/Order.java
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/main/java/seedu/sellsavvy/model/person/Name.java
  src/main/java/seedu/sellsavvy/model/person/Person.java
  src/main/java/seedu/sellsavvy/model/person/UniquePersonList.java
  src/main/java/seedu/sellsavvy/model/tag/Tag.java
  src/test/java/seedu/sellsavvy/commons/util/StringUtilTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/ListOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/DeletePersonCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/ListPersonCommandTest.java
  src/test/java/seedu/sellsavvy/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/EditOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/ListOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/MarkOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/ParserUtilTest.java
  src/test/java/seedu/sellsavvy/logic/parser/UnmarkOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/model/AddressBookTest.java
  src/test/java/seedu/sellsavvy/model/ModelManagerTest.java
  src/test/java/seedu/sellsavvy/model/order/ItemTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderTest.java
  src/test/java/seedu/sellsavvy/model/person/NameTest.java
  src/test/java/seedu/sellsavvy/model/person/PersonTest.java
  src/test/java/seedu/sellsavvy/model/person/UniquePersonListTest.java
  src/test/java/seedu/sellsavvy/model/tag/TagTest.java
  src/test/java/seedu/sellsavvy/testutil/TypicalIndexes.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#219 Update UG Quick Start for user-friendliness
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.Medium, severity.Medium, type.DocumentationBug, alpha-bug

#226 Update instructions for Customer Name
  docs/UserGuide.md
  src/main/java/seedu/sellsavvy/model/person/Name.java
Labels: priority.High, severity.Medium, type.FunctionalityBug, alpha-bug

#235 Rephrase alias notes in notes about command format in user guide
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.DocumentationBug, alpha-bug

#228 Update use case
  docs/DeveloperGuide.md
Labels: priority.High, type.DocumentationBug, alpha-bug

#231 Add warning about changing order status after filtering orders in ug
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.DocumentationBug, alpha-bug

#243 Update version number in MainApp
  src/main/java/seedu/sellsavvy/MainApp.java
Labels: type.Task, priority.High

#245 Update features in README
  README.md
Labels: priority.High, severity.Medium, type.DocumentationBug, alpha-bug

#246 Fix error in quick start in user guide
  docs/UserGuide.md
Labels: priority.High, type.DocumentationBug, alpha-bug

#249 Update UG constraints
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.DocumentationBug

#251 Update developer guide use cases
  docs/DeveloperGuide.md
  src/main/java/seedu/sellsavvy/MainApp.java
Labels: priority.High, severity.Medium, type.DocumentationBug, alpha-bug

#269 Update acknowledgement
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#311 Incorrect error message for index in edit order command
  docs/UserGuide.md
Labels: priority.Low, type.DocumentationBug

#310 Update UI screenshot
  docs/images/Ui.png
Labels: priority.Medium, severity.Low, type.DocumentationBug

#313 Fix Customer Name handling bug and constraints message error
  docs/UserGuide.md
  src/main/java/seedu/sellsavvy/model/customer/Name.java
Labels: type.Bug, priority.High, severity.Medium, type.FunctionalityBug

#321 Fix link in README.md site map
  README.md
Labels: priority.Medium, severity.Medium, type.DocumentationBug

#322 Fix bug where clear command does not clear order list
  src/main/java/seedu/sellsavvy/logic/commands/generalcommands/ClearCommand.java
Labels: type.Bug, priority.Medium, severity.Medium, type.FunctionalityBug

#316 Attach link to download Java 17
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.DocumentationBug

#312 Update UG Images for visual aid
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addOrder.png
  docs/images/filterCompletedOrders.png
  docs/images/filterOrderCompleted.png
  docs/images/findAlexDavidResult.png
  docs/images/listOrder.png
  docs/images/markOrder.png
  docs/images/unmarkOrder.png
Labels: priority.Medium, type.DocumentationBug

#330 Update DG Effort
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: priority.High, severity.Medium, type.DocumentationBug

#317 Add OrderList in alternative model in DG
  docs/diagrams/BetterModelClassDiagram.puml
Labels: priority.Medium, severity.Medium, type.DocumentationBug

#332 Fix javadoc
  src/main/java/seedu/sellsavvy/model/customer/Customer.java
Labels: priority.Low, severity.Low, type.DocumentationBug

#315 Update developer guide use cases
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: priority.High, severity.High, type.DocumentationBug

#329 Make command aliases singular under features in user guide
  docs/UserGuide.md
Labels: severity.VeryLow, type.DocumentationBug

#314 Update Implementation section of DG
  docs/DeveloperGuide.md
Labels: priority.High, severity.High, type.DocumentationBug

#319 Update UG bugs from PE-D
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.DocumentationBug

#334 Update effort in DG
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Task, priority.Medium

#327 Update UG warnings
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.DocumentationBug

#339 Fix link to #similar in DG
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Medium, type.DocumentationBug

#342 Fix breaks
  docs/DeveloperGuide.md
Labels: severity.Medium, type.DocumentationBug

#336 Add relevant planned enhancements
  docs/DeveloperGuide.md
  docs/images/longMessages.png
Labels: priority.High, severity.Medium, type.DocumentationBug

#344 Branch fix similar
  docs/DeveloperGuide.md
Labels: type.DocumentationBug

#340 Update Kai Xuan profile
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kaixuan.md
  docs/team/kaixuan477.md
Labels: type.Task, priority.Medium

#345 Fix markbind
  docs/DeveloperGuide.md
Labels: type.DocumentationBug

#347 Fix markbind
  docs/DeveloperGuide.md
Labels: type.DocumentationBug

#349 Add outdated notice
  docs/team/FooChao.md
Labels: type.Task, priority.Medium

#351 Update Kheng Yang profile
  docs/AboutUs.md
  docs/team/awdse22.md
  docs/team/khengyang.md
Labels: type.Task, priority.Medium

#362 Remove 'more user story to be added' for DG
  docs/DeveloperGuide.md
Labels: priority.Low, severity.VeryLow, type.DocumentationBug

#361 Fix nits and optimise user guide
  docs/UserGuide.md
Labels: severity.VeryLow, type.DocumentationBug

#335 Allow relationship indicator to be case-insensitive in planned enhanc…
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Medium, type.DocumentationBug

#358 Update version number of MainApp
  src/main/java/seedu/sellsavvy/MainApp.java
Labels: type.Task, priority.High

#382 Fix DG bugs
  docs/DeveloperGuide.md
Labels: severity.VeryLow, type.DocumentationBug

#391 Fix 'e.g.,'
  docs/DeveloperGuide.md
Labels: severity.VeryLow, type.DocumentationBug

#393 Add enhancement to allow identifying customers by name in dev guide
  docs/DeveloperGuide.md
Labels: type.DocumentationBug
