Repository AY2425S1-CS2103T-F14a-2/tp, pull requests merged in 2024-09, with the labels that each got.

#13 Update AboutUS page with Sutong's information
  docs/AboutUs.md
  docs/images/yu-sutong.png
  docs/team/yu-sutong.md
Labels: priority.High

#12 Update AboutUs.md with FooChao's detail
  docs/AboutUs.md
  docs/images/FooChao.png
  docs/team/FooChao.md
Labels: priority.High

#14 Update Kheng Yang's portfolio in AboutUs
  docs/AboutUs.md
  docs/images/awdse22.png
  docs/team/khengyang.md
Labels: priority.High

#17 Update README.md build status badge
  README.md
Labels: priority.High

#19 Add UI mockup to README
  docs/images/Ui.png
Labels: priority.High

#27 Add order and customer to glossary
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#30 Update Target User Profile, Value Proposition and User Stories in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#31 Update Non-functional Requirements in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#32 Fix spelling of SellSaavy in README.md
  README.md
Labels: priority.Medium

#35 Fix photo name
  docs/AboutUs.md
  docs/images/foochao.png
Labels: priority.Medium

#34 Remove traces of AB3 from README
  README.md
Labels: priority.High
