Repository AY2425S1-CS2103T-F14a-2/tp, pull requests merged in 2024-10, with the labels that each got.

#37 Update Use Cases in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#39 Incorporate Orders and Order List into Address Book
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/order/Count.java
  src/main/java/seedu/address/model/order/Date.java
  src/main/java/seedu/address/model/order/Item.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/OrderList.java
  src/main/java/seedu/address/model/order/exceptions/OrderNotFoundException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Epic, priority.High

#49 Re-package exit and help commands under GeneralCommand
  src/main/java/seedu/address/logic/commands/generalcommands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/generalcommands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#51 Update Javadoc for getAddPersonCommand for Person Util
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, priority.Medium, severity.VeryLow

#52 Re-package delete, edit and clear commands under PersonCommand
  src/main/java/seedu/address/logic/commands/generalcommands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/personcommands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/personcommands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/PersonCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#59 Implement AddOrder command
  src/main/java/seedu/sellsavvy/logic/Messages.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/sellsavvy/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/sellsavvy/logic/parser/AddressBookParser.java
  src/main/java/seedu/sellsavvy/logic/parser/CliSyntax.java
  src/main/java/seedu/sellsavvy/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/sellsavvy/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/sellsavvy/logic/parser/FindPersonCommandParser.java
  src/main/java/seedu/sellsavvy/model/AddressBook.java
  src/main/java/seedu/sellsavvy/model/Model.java
  src/main/java/seedu/sellsavvy/model/ModelManager.java
  src/main/java/seedu/sellsavvy/model/person/Person.java
  src/main/java/seedu/sellsavvy/model/person/UniquePersonList.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/OrderCommandTestUtil.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommandTest.java
  src/test/java/seedu/sellsavvy/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/sellsavvy/testutil/PersonBuilder.java
Labels: type.Story, priority.High

#66 Update User Guide for listOrder Command and FooChao.md
  README.md
  docs/UserGuide.md
  docs/team/FooChao.md
Labels: type.Story, priority.High

#72 Make the COUNT field for AddOrderCommand an optional field
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddOrderCommandParser.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/parser/AddOrderCommandParserTest.java
Labels: type.Task, priority.Medium

#70 Refactor SellSavvy Storage to Store Order Data
  src/main/java/seedu/sellsavvy/model/person/Person.java
  src/main/java/seedu/sellsavvy/storage/JsonAdaptedOrder.java
  src/main/java/seedu/sellsavvy/storage/JsonAdaptedPerson.java
  src/test/java/seedu/sellsavvy/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/sellsavvy/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/sellsavvy/testutil/PersonBuilder.java
  src/test/java/seedu/sellsavvy/testutil/TypicalOrders.java
  src/test/java/seedu/sellsavvy/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#79 Fix SellSavvy load storage operation
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/main/java/seedu/sellsavvy/storage/JsonAdaptedOrder.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
Labels: type.Bug, priority.High, severity.Medium

#80 Update AddressBook Storage Test Cases for Persons with Orders
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/sellsavvy/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Low

#82 Implement deleteOrder command
  docs/UserGuide.md
  src/main/java/seedu/sellsavvy/logic/Messages.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddressBookParser.java
  src/main/java/seedu/sellsavvy/logic/parser/DeleteOrderCommandParser.java
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
  src/test/java/seedu/sellsavvy/testutil/TypicalIndexes.java
Labels: type.Story, priority.High

#91 Re-add OrderUtil and AddressBookParser test case for AddOrderCommand
  docs/UserGuide.md
  src/test/java/seedu/sellsavvy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/sellsavvy/testutil/OrderUtil.java
Labels: type.Bug, priority.High

#97 Implement mark order command
  build.gradle
  docs/UserGuide.md
  docs/index.md
  docs/team/FooChao.md
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/sellsavvy/logic/parser/AddressBookParser.java
  src/main/java/seedu/sellsavvy/logic/parser/MarkOrderCommandParser.java
  src/main/java/seedu/sellsavvy/model/order/Order.java
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/main/java/seedu/sellsavvy/model/order/Status.java
  src/main/java/seedu/sellsavvy/model/person/Person.java
  src/main/java/seedu/sellsavvy/model/person/UniquePersonList.java
  src/main/java/seedu/sellsavvy/storage/JsonAdaptedOrder.java
  src/main/java/seedu/sellsavvy/ui/OrderCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/OrderStatus.css
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/MarkOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderTest.java
  src/test/java/seedu/sellsavvy/model/order/StatusTest.java
  src/test/java/seedu/sellsavvy/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/sellsavvy/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/sellsavvy/testutil/OrderBuilder.java
  src/test/java/seedu/sellsavvy/testutil/TypicalOrders.java
Labels: type.Story, priority.High

#105 Update UIClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task, priority.High

#100 Implement FilterOrder Command
  docs/UserGuide.md
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/ListOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddressBookParser.java
  src/main/java/seedu/sellsavvy/logic/parser/FilterOrderCommandParser.java
  src/main/java/seedu/sellsavvy/model/order/OrderList.java
  src/main/java/seedu/sellsavvy/model/order/StatusEqualsKeywordPredicate.java
  src/main/java/seedu/sellsavvy/model/person/Person.java
  src/main/java/seedu/sellsavvy/ui/OrderListPanel.java
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/FilterOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/FindPersonCommandParserTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
  src/test/java/seedu/sellsavvy/model/order/StatusEqualsKeywordPredicateTest.java
  src/test/java/seedu/sellsavvy/model/person/PersonTest.java
Labels: type.Story, priority.High

#108 Update Storage Class Diagram
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task, priority.High

#98 Implement EditOrder Command
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/DeletePersonCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddressBookParser.java
  src/main/java/seedu/sellsavvy/logic/parser/EditOrderCommandParser.java
  src/main/java/seedu/sellsavvy/model/AddressBook.java
  src/main/java/seedu/sellsavvy/model/Model.java
  src/main/java/seedu/sellsavvy/model/ModelManager.java
  src/main/java/seedu/sellsavvy/model/person/UniquePersonList.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderDescriptorTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/ListOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/OrderCommandTestUtil.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/DeletePersonCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommandTest.java
  src/test/java/seedu/sellsavvy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/EditOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/model/AddressBookTest.java
  src/test/java/seedu/sellsavvy/model/ModelManagerTest.java
  src/test/java/seedu/sellsavvy/model/person/UniquePersonListTest.java
  src/test/java/seedu/sellsavvy/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/sellsavvy/testutil/OrderUtil.java
  src/test/java/seedu/sellsavvy/testutil/TypicalIndexes.java
Labels: type.Story, priority.High

#111 Update DeleteSequenceCommand diagram
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task, priority.High

#114 Update ModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/style.puml
Labels: type.Task, priority.High

#137 Fix visual bug for filterOrder feedback in Start Case
  src/main/java/seedu/sellsavvy/model/order/Status.java
  src/main/java/seedu/sellsavvy/model/order/StatusEqualsKeywordPredicate.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommandTest.java
Labels: type.Bug, priority.Medium, severity.Low, alpha-bug

#136 Fix existing feature flaw that name does not allow / or '
  src/main/java/seedu/sellsavvy/model/person/Name.java
  src/test/java/seedu/sellsavvy/model/person/NameTest.java
Labels: type.Bug, priority.Medium, severity.Low

#122 Refactor model#getSelectedPerson method name
  src/main/java/seedu/sellsavvy/logic/Logic.java
  src/main/java/seedu/sellsavvy/logic/LogicManager.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/FilterOrderCommand.java
  src/main/java/seedu/sellsavvy/model/Model.java
  src/main/java/seedu/sellsavvy/model/ModelManager.java
  src/main/java/seedu/sellsavvy/ui/MainWindow.java
  src/test/java/seedu/sellsavvy/logic/LogicManagerTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/DeleteOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommandTest.java
  src/test/java/seedu/sellsavvy/model/ModelManagerTest.java
Labels: type.Enhancement, priority.Medium

#135 Fix visual bug where order display can be cut off
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#130 Refactor count to quantity
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/sellsavvy/logic/Messages.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/sellsavvy/logic/parser/CliSyntax.java
  src/main/java/seedu/sellsavvy/logic/parser/EditOrderCommandParser.java
  src/main/java/seedu/sellsavvy/logic/parser/ParserUtil.java
  src/main/java/seedu/sellsavvy/model/order/Order.java
  src/main/java/seedu/sellsavvy/model/order/Quantity.java
  src/main/java/seedu/sellsavvy/model/person/UniquePersonList.java
  src/main/java/seedu/sellsavvy/storage/JsonAdaptedOrder.java
  src/main/java/seedu/sellsavvy/ui/OrderCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderDescriptorTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/OrderCommandTestUtil.java
  src/test/java/seedu/sellsavvy/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/EditOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/ParserUtilTest.java
  src/test/java/seedu/sellsavvy/model/order/CountTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderListTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderTest.java
  src/test/java/seedu/sellsavvy/model/order/QuantityTest.java
  src/test/java/seedu/sellsavvy/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/sellsavvy/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/sellsavvy/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/sellsavvy/testutil/OrderBuilder.java
  src/test/java/seedu/sellsavvy/testutil/OrderUtil.java
  src/test/java/seedu/sellsavvy/testutil/TypicalOrders.java
Labels: type.Enhancement, priority.Medium

#140 Make EditOrder command give a warning if the date is in the past
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/parser/ParserUtil.java
  src/main/java/seedu/sellsavvy/model/order/Date.java
  src/main/java/seedu/sellsavvy/model/order/Order.java
  src/main/java/seedu/sellsavvy/storage/JsonAdaptedOrder.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/OrderCommandTestUtil.java
  src/test/java/seedu/sellsavvy/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/logic/parser/EditOrderCommandParserTest.java
  src/test/java/seedu/sellsavvy/model/order/DateTest.java
  src/test/java/seedu/sellsavvy/model/order/OrderTest.java
  src/test/java/seedu/sellsavvy/testutil/TypicalOrders.java
Labels: priority.Medium, severity.Medium, type.FeatureFlaw, alpha-bug

#132 Fix bug where addOrderCommand does not always list all orders
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java
Labels: priority.Medium, severity.Medium, type.FeatureFlaw, alpha-bug

#153 Update Quantity prefix to q/ to match name
  docs/UserGuide.md
  docs/UserGuide.md.rej
  src/main/java/seedu/sellsavvy/logic/parser/CliSyntax.java
Labels: priority.High, severity.Medium, type.FeatureFlaw, alpha-bug

#151 Update Order Item Regex to match Carousell's Documentation
  src/main/java/seedu/sellsavvy/model/order/Item.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/OrderCommandTestUtil.java
  src/test/java/seedu/sellsavvy/logic/parser/ParserUtilTest.java
  src/test/java/seedu/sellsavvy/model/order/ItemTest.java
Labels: priority.Medium, severity.Medium, type.FeatureFlaw, alpha-bug

#134 Update Sample Data to include orders
  src/main/java/seedu/sellsavvy/model/util/SampleDataUtil.java
Labels: type.Enhancement, priority.Low, alpha-bug

#157 Update code comments for class regex
  src/main/java/seedu/sellsavvy/model/order/Item.java
  src/main/java/seedu/sellsavvy/model/person/Name.java
  src/main/java/seedu/sellsavvy/model/util/SampleDataUtil.java
Labels: type.Bug, priority.Medium, severity.VeryLow, alpha-bug

#150 Change warning message to exception
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommand.java
  src/main/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommand.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/MarkOrderCommandTest.java
  src/test/java/seedu/sellsavvy/logic/commands/ordercommands/UnmarkOrderCommandTest.java
Labels: priority.High, alpha-bug

#154 Add period to Item's message constraints
  src/main/java/seedu/sellsavvy/model/order/Item.java
Labels: type.Bug, priority.Medium, severity.VeryLow, alpha-bug

#155 Add an example of a valid date when specifying the format of the date
  src/main/java/seedu/sellsavvy/model/order/Date.java
Labels: type.Enhancement, priority.Medium, alpha-bug
